language: ruby
rvm:
- 2.3.3
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - secure: wqjgRKbIko4dB5KinLhd/fQ8V538P36CVm74tVtlJcBtURb4Yv+Oa6MAOIwZOCjVW6K6f77Pqp2lEYBCvF/x/7gnDanSEXla9rZ/sNHKlJHvNWcqCiVRuoNAqLOr54ahjsT4jBEnT6MMHOYsddUwDduRkNLxQwqyb5LDsW5uVODjHt5KRmWWPVGu545ApnSNb5Cl1B/RLtyiuRJ1zBAFPLRI1TeH8/D04uhQXcr8SBkPjvE6gez/lUrlE3SLMU1nKHK3bPII+6eDbOJ1BN4aSVyH8hN0I60uSkkR2l0KcZx8qm/1ttWxzB2iHvJ2bKERLfmB+J8v1GrpZi/uWnq3S2uL5V3lmudGItf95/e0az1JywnHNb95skXEoyJ0sZqD6ugTcrX+jhFbQw3GdC4aa8yoNAk5z5fzQW4x2obwUttMnSsqZNHGgD7/Bx5RUaiHJWDwx+PQy+ljqM1ai5vpHGtBJLfxwB+RSNyVuAAEGX0L/Rt3AQHEFvstxp2YPk6XZ625rZgvtRif8GC1MYESABvYPzhrBnQUfELI8O10RW+mIuYY8clMYjgNaoI4u31L/UJTM46oqmzLn0ZS00Dv33/VDN0GH9Scap/BWTzmAHiLVCjmG4Ul9qSpaJfUfcrwl4cJP7M/d4SNh7TbbsUnh90GeI2bzvmsSZAmid1pBFY=
  - secure: p9U8FbTVFd2HHmpmcSEo1kwhGnCSno0ss+K56ifJdVdibkFLbjcKkIyo5Yh8S5kdOqiXTMaGnrTpRfuk8+lwQfHSILKKhIS3o5qYQbJqJY6SdQiVJRrOqofMYRq8UkuZrSFdrZG8fGaLcuXltq1qp5NmW8LIDD9wzMf6SZMYByvEB5PZT/aTnNIalR+7uwYw6BVFHYags7lfkJjTvzkCcz/hTVOf3oO/jNYUBVi2e+Fy5rj4pZj70aRVlEcRBbcs/k+Gzzun1OK4fvxvaJIhaqP7FgBZUvCeKeljhhoHPeQxZ5ORHhaipIumLUcvAKg7eEZ40Q9ekBwNQ7y6AuD4lzyNQHfe5aWVPvCa0qO2WbzagVxErf9JhZCyk2mozNXajfh0zICIE9ZZID6mrFBFgDGSqOQDx7jP0SCgVF2uufVNKaqqbTlNUiq8Dmb7rApYPPXLqTFgdbq7O88t2K+7XvF65jMrzs14NN0HMqZ2I2WY4PB/hx+XKXirKzsKgGxjSpwql1zHWyxFPxlPqJm67DFf9ZEP/OAJqrRX8CtkwltFO+eKvtd8Kt80ogH/bkz2Wsc5c0+Zp/F3+TjdPkK5uVP4QxDGrRr2qQ9xPVg0Txie7XE0T8faXbwzkcABwS6pJg12twDy2MGWVhHbhkcppXpCn7ip9l97isVUD7ywgeo=
after_success:
  "curl --ftp-create-dirs -T _site/README.md -u $FTP_USER:$FTP_PASSWORD ftp.gridhost.co.uk/public_html/tmp/"
