safe: true
lsi: false
future: true

kramdown:
  input: GFM
  hard_wrap: false

exclude: [vendor, README.md, Gemfile*, scripts, deploy_rsa*]

conference:
  current_year: 2017
  conference_year: spa2018
  name_html: <span class="conference-name">SPA<wbr><em>2018</em></span>
  dates: 2nd &ndash; 4th July 2018
