safe: true
lsi: false
future: true

kramdown:
  input: GFM
  hard_wrap: false

exclude: [vendor]

conference:
  conference_year: spa2018
  current_year: 2017
  name_html: <span class="conference-name">SPA<wbr><em>2018</em></span>
