safe: true
lsi: false
future: true

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  # Don't remove any of these, we do not want these on the server
  - vendor
  - README.md
  - Gemfile*
  - scripts
  - deploy_rsa*
  # BELOW are pages that are not yet published for this year
  # Comment out from this list when published
  # DO NOT comment back in, we do not want 404s
  # You can remove them from the menu (`_includes/menu.html`)
  - sponsors.md
  - refunds-and-cancellations.md
  - book-now.md
  - bofs.md

baseurl: /spa2018

conference:
  current_year: 2017
  conference_year: SPA2018
  name_html: <span class="conference-name">SPA<wbr><em>2018</em></span>
  name_with_year: SPA Software in Practice 2018
  dates: 2nd &ndash; 4th July 2018
  cfp_open_date: 30th November 2017
