safe: true
lsi: false
future: true

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  # Don't remove any of these, we do not want these on the server
  - vendor
  - README.md
  - Gemfile*
  - scripts
  - deploy_rsa*
  # BELOW are pages that are not yet published for this year
  # Comment out from this list when published
  # DO NOT comment back in, we do not want 404s
  # You can remove them from the menu by editing
  # conference.site_navigation, below
  # - sponsors.md
  # - book-now.md
  # - bofs.md

baseurl: /spa2018

conference:
  current_year: 2018
  name: SPA Software in Practice
  name_with_year: SPA Software in Practice 2018
  dates: 2nd &ndash; 4th July 2018
  cfp_open_date: 30th November 2017
  cfp_deadline_time: 10pm
  cfp_early_feedback_deadline: 21st January 2018
  cfp_close_date: 18th February 2018
  reviewing_deadline: 7th March 2018
  programme_meeting_date: 9th March 2018
  programme_announce_date: mid-April 2018
  shepherding_dates: 1st April &ndash; conference
  # This controls the site-wide navigation. Items should either be a
  # dictionary containing url and title, or the filename of the page to
  # link to (whose title will be the text of the link).
  # The order here dictates the display order, and items can be removed
  # by commenting out (or just deleting)
  site_navigation:
    -
      url: https://www.spaconference.org/spa2018/programme.html
      title: Programme
    # - sponsor.md
    - sponsors.md
    # - lead-a-session.md
    - organisers.md
    - location.md
    - previous-conferences.md
    - code-of-conduct.md
    - news.md
    -
      url: https://spaconference.org/scripts/myprofile.php
      title: My Spa
